packages:
  - libs/*
  - demo

ignoredBuiltDependencies:
  - esbuild
  - lmdb
  - rollup

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@angular/*"
  - "@angular-devkit/*"
  - "@schematics/angular"
