allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  rollup: false

packages:
  - libs/*
  - demo

minimumReleaseAge: 4320

overrides:
  sass: ^1.97.3 # without this, timeouts may occur in the tests
minimumReleaseAgeExclude:
  # Renovate security update: @angular/compiler@21.2.4
  - "@angular/compiler@21.2.4"
