packages:
  - libs/*
  - demo

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - rollup

minimumReleaseAge: 4320

overrides:
  undici@>=7.0.0 <7.18.2: ">=7.18.2"
