packages:
  - libs/*
  - demo

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  rollup: false

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@angular/*'
  - '@angular-devkit/*'
  - '@schematics/angular'
  - ng-packagr

catalog:
  '@angular/build': '22.0.5'
  '@angular/cdk': '22.0.3'
  '@angular/cli': '22.0.5'
  '@angular/common': '22.0.5'
  '@angular/compiler': '22.0.5'
  '@angular/compiler-cli': '22.0.5'
  '@angular/core': '22.0.5'
  '@angular/forms': '22.0.5'
  '@angular/material': '22.0.3'
  '@angular/platform-browser': '22.0.5'
  '@angular/router': '22.0.5'
  '@types/node': '24.13.2'
  '@vitest/browser-playwright': '4.1.9'
  '@vitest/coverage-v8': '4.1.9'
  angular-eslint: '22.0.0'
  cpy-cli: '7.0.0'
  dayjs: '1.11.21'
  eslint: '10.6.0'
  marked: '18.0.5'
  ng-packagr: '22.0.1'
  ngx-markdown: '22.0.0'
  oxfmt: '0.57.0'
  oxlint: '1.72.0'
  playwright: '1.61.1'
  prismjs: '1.30.0'
  rxjs: '7.8.2'
  tslib: '2.8.1'
  typescript: '6.0.3'
  typescript-eslint: '8.62.1'
  vitest: '4.1.9'
  zone.js: '0.16.2' # without this, the tests fail since Angular v22

dedupePeers: true

overrides:
  sass: ^1.99.0 # without this, timeouts may occur in the tests
