packages:
  - libs/*
  - demo

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  rollup: false

catalog:
  '@angular/build': '22.0.0-rc.0'
  '@angular/cdk': '22.0.0-rc.0'
  '@angular/cli': '22.0.0-rc.0'
  '@angular/common': '22.0.0-rc.0'
  '@angular/compiler': '22.0.0-rc.0'
  '@angular/compiler-cli': '22.0.0-rc.0'
  '@angular/core': '22.0.0-rc.0'
  '@angular/forms': '22.0.0-rc.0'
  '@angular/material': '22.0.0-rc.0'
  '@angular/platform-browser': '22.0.0-rc.0'
  '@angular/router': '22.0.0-rc.0'
  '@types/node': '24.12.4'
  '@vitest/browser-playwright': '4.1.6'
  '@vitest/coverage-v8': '4.1.6'
  angular-eslint: '21.4.0'
  cpy-cli: '7.0.0'
  dayjs: '1.11.20'
  eslint: '10.4.0'
  marked: '18.0.4'
  ng-packagr: '21.2.3'
  ngx-markdown: '21.3.0'
  oxfmt: '0.51.0'
  oxlint: '1.66.0'
  playwright: '1.60.0'
  prismjs: '1.30.0'
  rxjs: '7.8.2'
  tslib: '2.8.1'
  typescript: '6.0.3'
  typescript-eslint: '8.59.4'
  vitest: '4.1.6'
  zone.js: '0.16.2' # without this, the tests fail since Angular v22

dedupePeers: true

overrides:
  sass: ^1.99.0 # without this, timeouts may occur in the tests
