packages:
  - libs/*
  - demo

ignoredBuiltDependencies:
  - esbuild
  - lmdb
  - rollup
  - less
  - "@parcel/watcher"
  - msgpackr-extract

catalog:
  "@angular/build": 21.0.4

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@angular/*"
  - "@angular-devkit/*"
  - "@schematics/angular"
  - ng-packagr
